# This file is part of REANA.
# Copyright (C) 2026 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-24.04
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Prepare release
        id: release
        uses: googleapis/release-please-action@v5
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.ref_name }}

  release_assets:
    needs: release_please
    if: needs.release_please.outputs.release_created == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    with:
      release_tag: ${{ needs.release_please.outputs.tag_name }}
